### ISSUE TITLE
Create end scene

### ISSUE THREAD

**Issue by badman-dev** [badman-dev/SeniorDesign_SpaceGame#87]
Thanks for playing text, credits, art?

Scene change event fired from picking up objective asteroid, check tutorial/asteroid levels for how this is set up.

Scene should allow player to return to menu

**Comment by obrienep** [comment]
Final game sequence will go as follows:

Following final level results screen, move to end scene. Final graphic will show for a few seconds before text box similar to intro is displayed. Clicking next/okay on box sends player back to menu.

- [x]  End game graphic
- [ ] End game scene
- [ ] End game textbox implementation
